version: "3.7"
services:
  database:
    image: postgres
    environment:
      - "POSTGRES_DB=cadastro"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_USER=piaf"
    ports:
      - 5441:5432
    volumes:
      - pg-data:/data/postgres
volumes:
  pg-data:
    driver: local
 